# Generated by Django 6.0.1 on 2026-02-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Maqola",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sarlavha", models.CharField(max_length=200)),
                ("matn", models.TextField()),
                ("yaratilgan_sana", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
