# Generated by Django 6.0.1 on 2026-02-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_maqola_rasm"),
    ]

    operations = [
        migrations.AddField(
            model_name="maqola",
            name="manzil",
            field=models.CharField(
                blank=True, default="Noma'lum", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="maqola",
            name="telefon",
            field=models.CharField(
                blank=True, default="Ko'rsatilmagan", max_length=20, null=True
            ),
        ),
    ]
