# Generated by Django 6.0.1 on 2026-02-21 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_maqola_manzil_maqola_telefon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aloqa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ism", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("xabar", models.TextField()),
                ("yuborilgan_vaqt", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Izoh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("muallif", models.CharField(max_length=100)),
                ("matn", models.TextField()),
                ("yaratilgan_sana", models.DateTimeField(auto_now_add=True)),
                (
                    "maqola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="izohlar",
                        to="main.maqola",
                    ),
                ),
            ],
        ),
    ]
